### ISSUE TITLE
GWAS tutorial data.zip is not available

### ISSUE THREAD

**Issue by manarvaezco** [pbreheny/adv-gwas-tutorial#2]

**Comment by pbreheny** [comment]
Thanks for pointing this out...I've contacted Andrea Foulkes to see if this data is now being hosted somewhere else. I'll update this issue if/when I hear back.

**Comment by HediaTnani** [comment]
Any update?

**Comment by pbreheny** [comment]
Sorry this took so long! Probably seems very simple, but there was a lot of behind-the-scenes work involved in sharing these files.

Anyway, everything is up and running again -- the links on [this page](https://pbreheny.github.io/adv-gwas-tutorial/quality_control.html) now work.

Thank you for being patient!

**Comment by HediaTnani** [comment]
Thank you so much .
