### ISSUE TITLE
Fail to download the raw data

### ISSUE THREAD

**Issue by izengyx** [pbreheny/adv-gwas-tutorial#4]
Both zip and tar data failed to download.
https://d1d95ugxcvloeo.cloudfront.net/penncath.zip
https://d1d95ugxcvloeo.cloudfront.net/penncath.tar.gz

**Comment by pbreheny** [comment]
Thank you for bringing this to my attention! Fixed now 78b6b85377045794e7028e475d6812da28d90539

**Comment by izengyx** [comment]
> Thank you for bringing this to my attention! Fixed now 78b6b85377045794e7028e475d6812da28d90539

Thank you so much！
